/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AuthLoginRouteImport } from './pages/_auth/login'
import { Route as AppWorkdayV2RouteImport } from './pages/_app/workday-v2'
import { Route as AppWorkdayRouteImport } from './pages/_app/workday'
import { Route as AppTasksRouteImport } from './pages/_app/tasks'
import { Route as AppPointRouteImport } from './pages/_app/point'
import { Route as AppHistoryRouteImport } from './pages/_app/history'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppWorkdayV2Route = AppWorkdayV2RouteImport.update({
  id: '/workday-v2',
  path: '/workday-v2',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppWorkdayRoute = AppWorkdayRouteImport.update({
  id: '/workday',
  path: '/workday',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPointRoute = AppPointRouteImport.update({
  id: '/point',
  path: '/point',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/history': typeof AppHistoryRoute
  '/point': typeof AppPointRoute
  '/tasks': typeof AppTasksRoute
  '/workday': typeof AppWorkdayRoute
  '/workday-v2': typeof AppWorkdayV2Route
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/history': typeof AppHistoryRoute
  '/point': typeof AppPointRoute
  '/tasks': typeof AppTasksRoute
  '/workday': typeof AppWorkdayRoute
  '/workday-v2': typeof AppWorkdayV2Route
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/point': typeof AppPointRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/workday': typeof AppWorkdayRoute
  '/_app/workday-v2': typeof AppWorkdayV2Route
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/point'
    | '/tasks'
    | '/workday'
    | '/workday-v2'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/point'
    | '/tasks'
    | '/workday'
    | '/workday-v2'
    | '/login'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/history'
    | '/_app/point'
    | '/_app/tasks'
    | '/_app/workday'
    | '/_app/workday-v2'
    | '/_auth/login'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/workday-v2': {
      id: '/_app/workday-v2'
      path: '/workday-v2'
      fullPath: '/workday-v2'
      preLoaderRoute: typeof AppWorkdayV2RouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/workday': {
      id: '/_app/workday'
      path: '/workday'
      fullPath: '/workday'
      preLoaderRoute: typeof AppWorkdayRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/point': {
      id: '/_app/point'
      path: '/point'
      fullPath: '/point'
      preLoaderRoute: typeof AppPointRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppPointRoute: typeof AppPointRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWorkdayRoute: typeof AppWorkdayRoute
  AppWorkdayV2Route: typeof AppWorkdayV2Route
  AppIndexRoute: typeof AppIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppPointRoute: AppPointRoute,
  AppTasksRoute: AppTasksRoute,
  AppWorkdayRoute: AppWorkdayRoute,
  AppWorkdayV2Route: AppWorkdayV2Route,
  AppIndexRoute: AppIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
